In [1]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.metrics.pairwise import euclidean_distances
import math
import matplotlib.pyplot as plt
import warnings
import numpy as np
warnings.simplefilter('ignore')

In [11]:
df = pd.read_excel('AmesHousing.xlsx')
df

,ID,SalePrice,Garage,Overall Qual,Gr Liv Area,Total Bsmt SF,Lot Area,Year Built,Full Bath,Bedroom AbvGr,Neighborhood,House Style
0,1,215000,yes,6,1656,1080.0,31770,1960,1,3,NAmes,1Story
1,2,105000,yes,5,896,882.0,11622,1961,1,2,NAmes,1Story
2,3,172000,yes,6,1329,1329.0,14267,1958,1,3,NAmes,1Story
3,4,244000,yes,7,2110,2110.0,11160,1968,2,3,NAmes,1Story
4,5,189900,yes,5,1629,928.0,13830,1997,2,3,Gilbert,2Story
...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,142500,yes,6,1003,1003.0,7937,1984,1,3,Mitchel,SLvl
2926,2927,131000,yes,5,902,864.0,8885,1983,1,2,Mitchel,1Story
2927,2928,132000,no,5,970,912.0,10441,1992,1,3,Mitchel,SFoyer
2928,2929,170000,yes,5,1389,1389.0,10010,1974,1,2,Mitchel,1Story
2929,2930,188000,yes,7,2000,996.0,9627,1993,2,3,Mitchel,2Story

In [12]:
df = df.loc[:, ['SalePrice', 'House Style', 'Gr Liv Area']]
df

      SalePrice House Style  Gr Liv Area
0        215000      1Story         1656
1        105000      1Story          896
2        172000      1Story         1329
3        244000      1Story         2110
4        189900      2Story         1629
...         ...         ...          ...
2925     142500        SLvl         1003
2926     131000      1Story          902
2927     132000      SFoyer          970
2928     170000      1Story         1389
2929     188000      2Story         2000

[2930 rows x 3 columns]

In [13]:
dummies_df = pd.get_dummies(df.loc[:, ("House Style")])
dummies_df

      1.5Fin  1.5Unf  1Story  2.5Fin  2.5Unf  2Story  SFoyer   SLvl
0      False   False    True   False   False   False   False  False
1      False   False    True   False   False   False   False  False
2      False   False    True   False   False   False   False  False
3      False   False    True   False   False   False   False  False
4      False   False   False   False   False    True   False  False
...      ...     ...     ...     ...     ...     ...     ...    ...
2925   False   False   False   False   False   False   False   True
2926   False   False    True   False   False   False   False  False
2927   False   False   False   False   False   False    True  False
2928   False   False    True   False   False   False   False  False
2929   False   False   False   False   False    True   False  False

[2930 rows x 8 columns]

In [14]:
df = pd.concat([df, dummies_df], axis=1)
df = df.drop(["House Style"], axis=1)
# df = df.drop(["Neighborhood"], axis=1)

df

,SalePrice,Gr Liv Area,1.5Fin,1.5Unf,1Story,2.5Fin,2.5Unf,2Story,SFoyer,SLvl
0,215000,1656,False,False,True,False,False,False,False,False
1,105000,896,False,False,True,False,False,False,False,False
2,172000,1329,False,False,True,False,False,False,False,False
3,244000,2110,False,False,True,False,False,False,False,False
4,189900,1629,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
2925,142500,1003,False,False,False,False,False,False,False,True
2926,131000,902,False,False,True,False,False,False,False,False
2927,132000,970,False,False,False,False,False,False,True,False
2928,170000,1389,False,False,True,False,False,False,False,False
2929,188000,2000,False,False,False,False,False,True,False,False

In [15]:
df_2d = df.loc[:, ['SalePrice', 'Gr Liv Area']]
df_2d

      SalePrice  Gr Liv Area
0        215000         1656
1        105000          896
2        172000         1329
3        244000         2110
4        189900         1629
...         ...          ...
2925     142500         1003
2926     131000          902
2927     132000          970
2928     170000         1389
2929     188000         2000

[2930 rows x 2 columns]

In [16]:
aantal_klusters = 3
kmean = KMeans(n_clusters=aantal_klusters, random_state=1)
kmean.fit_predict(df_2d)

array([1, 0, 0, ..., 0, 0, 1], shape=(2930,), dtype=int32)

In [18]:
kmeans_centra = pd.DataFrame(kmean.cluster_centers_, columns=['SalePrice', 'Gr Liv Area'])
kmeans_centra.index.name = 'Cluster'
kmeans_centra

             SalePrice  Gr Liv Area
Cluster
0        130012.073565  1245.729067
1        218012.916174  1732.649901
2        374127.754098  2271.831967

In [19]:
afstanden_tot_centra = pd.DataFrame(euclidean_distances(df_2d, kmeans_centra), index = df_2d.index)
afstanden_tot_centra

                  0              1              2
0      84988.916701    3013.891019  159128.945743
1      25014.518473  113016.013047  269131.270832
2      41988.009007   46014.686656  202129.953023
3     113991.202894   25989.823372  130127.854729
4      59889.152852   28113.107247  184228.875622
...             ...            ...            ...
2925   12490.285187   75516.441243  231631.229335
2926    1046.015446   87016.880893  243131.613026
2927    2006.957406   86016.297197  242131.253809
2928   39988.183094   48014.145986  204129.663169
2929   57992.831772   30014.106905  186127.952598

[2930 rows x 3 columns]

In [ ]:
plt.figure(figsize=(8, 6))

for cluster_id, group in df_2d.groupby(kmean.labels_):
    plt.scatter(
        group['SalePrice'],
        group['Gr Liv Area'],
        label=f'{cluster_id}',
        alpha=0.7,
        s=60
    )

plt.xlabel('SalePrice')
plt.ylabel('Gr Liv Area')
plt.title('Clusteren')
plt.legend()
plt.grid(True)
plt.show()

KeyError: 'Cluster'