In [86]:
import pandas as pd

from sklearn.model_selection import train_test_split 
from sklearn import linear_model
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error 
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler 
import matplotlib.pyplot as plt

Maak een Jupyter Notebook waarin je het tabje “AmesHousing” van het bestand AmesHousing.xlsx inleest, als DataFrame in Python. Zorg ervoor dat elke Excel-kolom overeenkomt met een DataFrame-kolom.

In [87]:
dataset = pd.read_excel('AmesHousing.xlsx')
dataset

,ID,SalePrice,Garage,Overall Qual,Gr Liv Area,Total Bsmt SF,Lot Area,Year Built,Full Bath,Bedroom AbvGr,Neighborhood,House Style
0,1,215000,yes,6,1656,1080.0,31770,1960,1,3,NAmes,1Story
1,2,105000,yes,5,896,882.0,11622,1961,1,2,NAmes,1Story
2,3,172000,yes,6,1329,1329.0,14267,1958,1,3,NAmes,1Story
3,4,244000,yes,7,2110,2110.0,11160,1968,2,3,NAmes,1Story
4,5,189900,yes,5,1629,928.0,13830,1997,2,3,Gilbert,2Story
...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,142500,yes,6,1003,1003.0,7937,1984,1,3,Mitchel,SLvl
2926,2927,131000,yes,5,902,864.0,8885,1983,1,2,Mitchel,1Story
2927,2928,132000,no,5,970,912.0,10441,1992,1,3,Mitchel,SFoyer
2928,2929,170000,yes,5,1389,1389.0,10010,1974,1,2,Mitchel,1Story
2929,2930,188000,yes,7,2000,996.0,9627,1993,2,3,Mitchel,2Story

Open AmesHousing.xlsx in Excel en lees de inhoud van het tabje “Data Dictionary” goed door. Deze geeft de betekenis weer van elke feature én van de targetvariabele. Zoek uit in welke kolom de targetvariabele staat en maak een top 3 van features waarvan je verwacht dat die het meest voorspellend zijn voor de targetvariabele. Let op: minstens één van deze features moet categorisch zijn! Noteer de gekozen features en het target in je logboek.

In [88]:
'''
De target variable is SalePrice
Mijn gekozen features zijn:
House Style	
Overall Qual
Gr Liv Area
'''

'\nDe target variable is SalePrice\nMijn gekozen features zijn:\nHouse Style\t\nOverall Qual\nGr Liv Area\n'

Prepareer je data in je Jupyter Notebook:
    -One-hot encode je uitgekozen categorische feature(s)
    -Splits de dataset horizontaal én verticaal, zodat er vier “stukken” ontstaan.

In [89]:
#dataset = dataset.loc[:,['SalePrice', 'Overall Qual',	'Gr Liv Area',	'Neighborhood', 'House Style']]
dataset

,ID,SalePrice,Garage,Overall Qual,Gr Liv Area,Total Bsmt SF,Lot Area,Year Built,Full Bath,Bedroom AbvGr,Neighborhood,House Style
0,1,215000,yes,6,1656,1080.0,31770,1960,1,3,NAmes,1Story
1,2,105000,yes,5,896,882.0,11622,1961,1,2,NAmes,1Story
2,3,172000,yes,6,1329,1329.0,14267,1958,1,3,NAmes,1Story
3,4,244000,yes,7,2110,2110.0,11160,1968,2,3,NAmes,1Story
4,5,189900,yes,5,1629,928.0,13830,1997,2,3,Gilbert,2Story
...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,142500,yes,6,1003,1003.0,7937,1984,1,3,Mitchel,SLvl
2926,2927,131000,yes,5,902,864.0,8885,1983,1,2,Mitchel,1Story
2927,2928,132000,no,5,970,912.0,10441,1992,1,3,Mitchel,SFoyer
2928,2929,170000,yes,5,1389,1389.0,10010,1974,1,2,Mitchel,1Story
2929,2930,188000,yes,7,2000,996.0,9627,1993,2,3,Mitchel,2Story

In [90]:
Style1 = pd.get_dummies(dataset.loc[:, 'Neighborhood'], drop_first=True)
Style1
Style2 = pd.get_dummies(dataset.loc[:, 'House Style'], drop_first=True)
Style2
Style3 = pd.get_dummies(dataset.loc[:, 'Garage'], drop_first=True)
Style3

        yes
0      True
1      True
2      True
3      True
4      True
...     ...
2925   True
2926   True
2927  False
2928   True
2929   True

[2930 rows x 1 columns]

In [91]:
dataset = pd.concat([dataset, Style1], axis=1)
dataset = pd.concat([dataset, Style2], axis=1)
dataset = pd.concat([dataset, Style3], axis=1)
dataset = dataset.drop(['Neighborhood', 'House Style', 'Garage'], axis=1)
dataset

,ID,SalePrice,Overall Qual,Gr Liv Area,Total Bsmt SF,Lot Area,Year Built,Full Bath,Bedroom AbvGr,Blueste,...,Timber,Veenker,1.5Unf,1Story,2.5Fin,2.5Unf,2Story,SFoyer,SLvl,yes
0,1,215000,6,1656,1080.0,31770,1960,1,3,False,...,False,False,False,True,False,False,False,False,False,True
1,2,105000,5,896,882.0,11622,1961,1,2,False,...,False,False,False,True,False,False,False,False,False,True
2,3,172000,6,1329,1329.0,14267,1958,1,3,False,...,False,False,False,True,False,False,False,False,False,True
3,4,244000,7,2110,2110.0,11160,1968,2,3,False,...,False,False,False,True,False,False,False,False,False,True
4,5,189900,5,1629,928.0,13830,1997,2,3,False,...,False,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,2926,142500,6,1003,1003.0,7937,1984,1,3,False,...,False,False,False,False,False,False,False,False,True,True
2926,2927,131000,5,902,864.0,8885,1983,1,2,False,...,False,False,False,True,False,False,False,False,False,True
2927,2928,132000,5,970,912.0,10441,1992,1,3,False,...,False,False,False,False,False,False,False,True,False,False
2928,2929,170000,5,1389,1389.0,10010,1974,1,2,False,...,False,False,False,True,False,False,False,False,False,True
2929,2930,188000,7,2000,996.0,9627,1993,2,3,False,...,False,False,False,False,False,False,True,False,False,True

In [92]:
X = dataset.loc[dataset['SalePrice'].notna(), :].drop('SalePrice', axis=1)
Y = dataset.loc[dataset['SalePrice'].notna(), 'SalePrice']

X['Total Bsmt SF'] = X['Total Bsmt SF'].fillna(X['Total Bsmt SF'].median())

In [93]:
X_train, X_test, Y_train,  Y_test = train_test_split(
    X,
    Y,
    test_size=0.15,
    random_state=42

)

In [94]:
model = LinearRegression()
model = model.fit(X_train, Y_train)
model.score(X_train, Y_train)

0.8256429704841886

In [95]:
Y_pred = model.predict(X_test)
mean_absolute_error(Y_test, Y_pred)

21478.380772891265

In [96]:
mean_squared_error(Y_test, Y_pred)

1243197756.1025188

Logboek hier want heb geen zin om excel bestand te maken

In [97]:
logboek = pd.DataFrame([
    {
        'Features': 'Overall Qual + Gr Liv Area  +House Style',
        'Feature aantal': '3',
        'R2score': 0.7652799916874008,
        'Mean absolute error': 27233.683460052944,
        'Mean squared error': 1696556276.3488176
    },
    {
    "Features": "Total Bsmt SF + House Style + Gr Liv Area",
    "Feature aantal": "3",
    "R2score": 0.6339976697740846,
    "Mean absolute error": 30234.64770679482,
    'Mean squared error': 2302766639.230193
    },
    {
    "Features": "Overall Qual + Garage + Gr Liv Area",
    "Feature aantal": "3",
    "R2score": 0.7302377660290891,
    "Mean absolute error": 30052.035841744375,
    'Mean squared error':1985393849.680396
    },
    {
    "Features": "Overall Qual + Neighbourhood + Gr Liv Area",
    "Feature aantal": "3",
    "R2score": 0.7713026037238904,
    "Mean absolute error": 24657.423437970414,
    'Mean squared error': 1519212074.4158592
    },
    {
    "Features": "Full Bath + Gr Liv Area + Total Bsmt SF",
    "Feature aantal": "3",
    "R2score": 0.6235493006291759,
    "Mean absolute error": 30632.987807731326,
    'Mean squared error': 2391321182.471727
    },
    {
    "Features": "Overall Qual + Neighborhood + Lot Area",
    "Feature aantal": "3",
    "R2score": 0.7409224574670155,
    "Mean absolute error": 28399.647636253678,
    'Mean squared error': 1752067610.436166
    },
    {
    "Features": "Overall Qual + Bedroom AbvGr + Gr Liv Area",
    "Feature aantal": "3",
    "R2score": 0.7409736810679874,
    "Mean absolute error": 29707.01387072196,
    'Mean squared error': 1928888270.027976
    },
    {
    "Features": "Overall Qual + Gr Liv Area + Neighborhood + House Style",
    "Feature aantal": "4",
    "R2score": 0.8119671543342439,
    "Mean absolute error": 22938.188578978377,
    'Mean squared error': 1319527227.785899
    },
    {
    "Features": "alle",
    "Feature aantal": "niet geteld",
    "R2score": 0.8256429704841886,
    "Mean absolute error": 21478.380772891265,
    'Mean squared error': 1243197756.1025188
    }
])
logboek

,Features,Feature aantal,R2score,Mean absolute error,Mean squared error
0,Overall Qual + Gr Liv Area +House Style,3,0.765280,27233.683460,1.696556e+09
1,Total Bsmt SF + House Style + Gr Liv Area,3,0.633998,30234.647707,2.302767e+09
2,Overall Qual + Garage + Gr Liv Area,3,0.730238,30052.035842,1.985394e+09
3,Overall Qual + Neighbourhood + Gr Liv Area,3,0.771303,24657.423438,1.519212e+09
4,Full Bath + Gr Liv Area + Total Bsmt SF,3,0.623549,30632.987808,2.391321e+09
5,Overall Qual + Neighborhood + Lot Area,3,0.740922,28399.647636,1.752068e+09
6,Overall Qual + Bedroom AbvGr + Gr Liv Area,3,0.740974,29707.013871,1.928888e+09
7,Overall Qual + Gr Liv Area + Neighborhood + Ho...,4,0.811967,22938.188579,1.319527e+09
8,alle,niet geteld,0.825643,21478.380773,1.243198e+09

In [ ]:
nieuwe_rijen = pd.DataFrame([
{
"Features": "",
"Feature aantal": "",
"R2score": 0,
"Mean absolute error": 0,
'Mean squared error': 0
}
])